version: "3.9"
services:
  postgres:
    image: timescale/timescaledb:latest-pg13
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - ./data_volumes/postgresdb/data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data_volumes/redis/data:/data

  cassandra:
    image: cassandra:latest
    environment:
      CASSANDRA_SEEDS: cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./data_volumes/cassandra/data:/var/lib/cassandra


