version: "3.9"
services:
  postgres:
    volumes:
      - ./data_volumes/postgres/data:/var/lib/postgresql/data
      
  redis:
    volumes:
      - ./data_volumes/redis/data:/var/???
  
  cassandra:
    volumes:
      - ./data_volumes/cassandra/data:/var/???
        
  kafka:
    volumes:
      - ./data_volumes/kafka/data:/var/???
        
  boltdb:
    volumes:
      - ./data_volumes/boltdb/data:/var/???
        

# TODO: сделать запуск каждой бд

