version: "3.9"
services:
  postgres:
    image: timescale/timescaledb:latest-pg13
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - ./data_volumes/postgres/data:/var/lib/postgresql/data

# TODO: сделать запуск redis и cassandra

#  redis:
#    volumes:
#      - ./data_volumes/redis/data:/var/???
#
#  cassandra:
#    volumes:
#      - ./data_volumes/cassandra/data:/var/???
#
#

